services:
  erp-tenant:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - bin/
            - obj/
    container_name: tenant-service
    ports:
      - "5008:8080"
    env_file:
      - .env
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - erp-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tenant-sqlserver
    environment:
      SA_PASSWORD: ${SQLSERVER__SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1440:1433"
    healthcheck:
      test: "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${SQLSERVER__SA_PASSWORD}' -Q 'SELECT 1' -C"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - erp-network

networks:
  erp-network:
    external: true
    name: erp-network